# Generated by Django 4.2.23 on 2025-08-20 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OmokGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('ai', 'AI와 대결'), ('friend', '친구와 대결')], default='ai', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움'), ('expert', '전문가')], default='normal', max_length=20)),
                ('board_state', models.TextField(default='[["" for _ in range(15)] for _ in range(15)]')),
                ('current_player', models.CharField(default='black', max_length=20)),
                ('game_status', models.CharField(choices=[('waiting', '대기 중'), ('playing', '진행 중'), ('finished', '종료')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('ai_strategy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmokMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.CharField(max_length=20)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('round_number', models.IntegerField()),
                ('ai_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='omok.omokgame')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
