# Generated by Django 4.2.23 on 2025-08-21 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='방 이름', max_length=100)),
                ('game_type', models.CharField(choices=[('baseball', '숫자야구'), ('omok', '오목'), ('wordchain', '끝말잇기'), ('baskin31', '바스킨31'), ('gonu', '고누')], help_text='게임 종류', max_length=20)),
                ('room_status', models.CharField(choices=[('waiting', '대기 중'), ('playing', '게임 중'), ('finished', '종료')], default='waiting', max_length=20)),
                ('max_players', models.IntegerField(default=4, help_text='최대 플레이어 수')),
                ('difficulty', models.CharField(default='normal', help_text='게임 난이도', max_length=20)),
                ('is_private', models.BooleanField(default=False, help_text='비공개 방 여부')),
                ('password', models.CharField(blank=True, help_text='방 비밀번호', max_length=100, null=True)),
                ('creator', models.CharField(default='Unknown', help_text='방장 닉네임', max_length=100)),
                ('creator_id', models.CharField(default='', help_text='방장 ID', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(help_text='플레이어 닉네임', max_length=50)),
                ('session_id', models.CharField(help_text='세션 ID', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
                ('is_ready', models.BooleanField(default=False, help_text='준비 상태')),
                ('total_games', models.IntegerField(default=0, help_text='총 게임 수')),
                ('wins', models.IntegerField(default=0, help_text='승리 수')),
                ('losses', models.IntegerField(default=0, help_text='패배 수')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='multiplayer.gameroom')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_data', models.JSONField(default=dict, help_text='게임 데이터')),
                ('current_turn', models.CharField(blank=True, help_text='현재 차례 플레이어', max_length=100, null=True)),
                ('round_number', models.IntegerField(default=1, help_text='현재 라운드')),
                ('max_rounds', models.IntegerField(default=10, help_text='최대 라운드')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_action_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='multiplayer.gameroom')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('chat', '일반 채팅'), ('system', '시스템 메시지'), ('game', '게임 관련')], default='chat', max_length=20)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='multiplayer.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='multiplayer.gameroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
