# Generated by Django 4.2.23 on 2025-08-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_number', models.CharField(max_length=10)),
                ('digit_count', models.IntegerField(default=3)),
                ('max_rounds', models.IntegerField(default=20)),
                ('current_round', models.IntegerField(default=1)),
                ('game_status', models.CharField(choices=[('waiting', '대기 중'), ('playing', '진행 중'), ('finished', '종료')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움'), ('expert', '전문가')], default='normal', max_length=20)),
                ('ai_hints', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaseballGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.CharField(max_length=10)),
                ('strikes', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('round_number', models.IntegerField()),
                ('ai_hint', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='baseball.baseballgame')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
