# Generated by Django 4.2.23 on 2025-08-21 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI Player', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움'), ('expert', '전문가')], max_length=10)),
                ('win_count', models.IntegerField(default=0)),
                ('loss_count', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('average_rounds', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-total_games'],
            },
        ),
        migrations.RemoveField(
            model_name='baseballgame',
            name='ai_hints',
        ),
        migrations.RemoveField(
            model_name='baseballgame',
            name='player',
        ),
        migrations.RemoveField(
            model_name='baseballgame',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='ai_opponent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='current_player',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='player_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='secret_number_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('normal', '보통'), ('hard', '어려움'), ('expert', '전문가')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='digit_count',
            field=models.IntegerField(default=3, help_text='자릿수'),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='game_status',
            field=models.CharField(choices=[('waiting', '대기 중'), ('playing', '진행 중'), ('finished', '종료')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='secret_number',
            field=models.CharField(help_text='정답 숫자', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baseballguess',
            name='ai_hint',
            field=models.TextField(blank=True, help_text='AI 힌트'),
        ),
        migrations.AlterField(
            model_name='baseballguess',
            name='balls',
            field=models.IntegerField(default=0, help_text='볼 수'),
        ),
        migrations.AlterField(
            model_name='baseballguess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='baseballguess',
            name='guess_number',
            field=models.CharField(help_text='추측한 숫자', max_length=10),
        ),
        migrations.AlterField(
            model_name='baseballguess',
            name='round_number',
            field=models.IntegerField(help_text='라운드 번호'),
        ),
        migrations.AlterField(
            model_name='baseballguess',
            name='strikes',
            field=models.IntegerField(default=0, help_text='스트라이크 수'),
        ),
    ]
