# Generated by Django 4.2.23 on 2025-08-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordChainGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_word', models.CharField(max_length=50)),
                ('used_words', models.TextField(default='[]')),
                ('game_status', models.CharField(choices=[('waiting', '대기 중'), ('playing', '진행 중'), ('finished', '종료')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('difficulty', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordChainWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=50)),
                ('round_number', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_message', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wordchain.wordchaingame')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
